site_title = "MyArxiv"
limit_days = 365
cache_url = "https://yiboz2001.github.io/MyArxiv/cache.json"

[[sources]]
limit = 1000
category = "cs.CV"
title = "Computer Vision and Pattern Recognition"

[scripts]
highlight_title = "scripts/highlight_title.rhai"
highlight_author = "scripts/highlight_author.rhai"
highlight_conference = "scripts/highlight_conference.rhai"
